// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSI14930_c072073.Context;

#nullable disable

namespace PSI14930_c072073.Migrations
{
    [DbContext(typeof(SimulacaoInvestimentoPerfilContext))]
    partial class SimulacaoInvestimentoPerfilContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PSI14930_c072073.Model.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Cliente que busca segurança",
                            Perfil = "Conservador",
                            Pontuacao = 50
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Cliente com perfil equilibrado entre segurança e rentabilidade",
                            Perfil = "Moderado",
                            Pontuacao = 70
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Cliente que procura alta rentabilidade",
                            Perfil = "Agressivo",
                            Pontuacao = 90
                        });
                });

            modelBuilder.Entity("PSI14930_c072073.Model.HistoricoInvestimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdProduto");

                    b.ToTable("HistoricoInvestimentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Data = new DateOnly(2025, 1, 10),
                            IdCliente = 1,
                            IdProduto = 1,
                            Valor = 1000.0
                        },
                        new
                        {
                            Id = 2,
                            Data = new DateOnly(2025, 2, 15),
                            IdCliente = 1,
                            IdProduto = 2,
                            Valor = 1500.0
                        },
                        new
                        {
                            Id = 3,
                            Data = new DateOnly(2025, 3, 20),
                            IdCliente = 2,
                            IdProduto = 3,
                            Valor = 2000.0
                        },
                        new
                        {
                            Id = 4,
                            Data = new DateOnly(2025, 4, 25),
                            IdCliente = 2,
                            IdProduto = 2,
                            Valor = 3500.0
                        },
                        new
                        {
                            Id = 5,
                            Data = new DateOnly(2025, 5, 30),
                            IdCliente = 3,
                            IdProduto = 3,
                            Valor = 6000.0
                        },
                        new
                        {
                            Id = 6,
                            Data = new DateOnly(2025, 6, 5),
                            IdCliente = 3,
                            IdProduto = 2,
                            Valor = 2000.0
                        });
                });

            modelBuilder.Entity("PSI14930_c072073.Model.HistoricoSimulacaoInvestimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int");

                    b.Property<int>("Prazo")
                        .HasColumnType("int");

                    b.Property<double>("ValorFinal")
                        .HasColumnType("float");

                    b.Property<double>("ValorInvestido")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdProduto");

                    b.ToTable("HistoricoSimulacaoInvestimentos");
                });

            modelBuilder.Entity("PSI14930_c072073.Model.HistoricoSimulacaoPerfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<bool>("Liquidez")
                        .HasColumnType("bit");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("int");

                    b.Property<int>("Prazo")
                        .HasColumnType("int");

                    b.Property<bool>("Rentabilidade")
                        .HasColumnType("bit");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("HistoricoSimulacaoPerfis");
                });

            modelBuilder.Entity("PSI14930_c072073.Model.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rentabilidade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Risco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "CDB Caixa 2026",
                            Rentabilidade = 0.12m,
                            Risco = "Baixo",
                            Tipo = "CDB"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "FundoXPTO",
                            Rentabilidade = 0.10m,
                            Risco = "Médio",
                            Tipo = "Fundo"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Ações",
                            Rentabilidade = 0.20m,
                            Risco = "Alto",
                            Tipo = "Bolsa de Valores"
                        });
                });

            modelBuilder.Entity("PSI14930_c072073.Model.HistoricoInvestimento", b =>
                {
                    b.HasOne("PSI14930_c072073.Model.Cliente", "Cliente")
                        .WithMany("Investimentos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PSI14930_c072073.Model.Produto", "Produto")
                        .WithMany("Investimentos")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("PSI14930_c072073.Model.HistoricoSimulacaoInvestimento", b =>
                {
                    b.HasOne("PSI14930_c072073.Model.Cliente", "Cliente")
                        .WithMany("Simulacoes")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PSI14930_c072073.Model.Produto", "Produto")
                        .WithMany("Simulacoes")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("PSI14930_c072073.Model.Cliente", b =>
                {
                    b.Navigation("Investimentos");

                    b.Navigation("Simulacoes");
                });

            modelBuilder.Entity("PSI14930_c072073.Model.Produto", b =>
                {
                    b.Navigation("Investimentos");

                    b.Navigation("Simulacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
